version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - inventory-net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: inventory_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-dbas-jkt-001.sumobase.my.id
      PMA_PORT: 63306
    ports:
      - "8080:80"
    networks:
      - inventory-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: inventory_cloudflared
    restart: unless-stopped
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared:/etc/cloudflared
    depends_on:
      - app
    networks:
      - inventory-net

networks:
  inventory-net:
    driver: bridge
