tunnel: a49b630f-de89-4ffd-b493-cb2e0e85797b
credentials-file: /etc/cloudflared/a49b630f-de89-4ffd-b493-cb2e0e85797b.json

ingress:
  - hostname: zahdikafahriza.web.id
    service: http://app:8000
  - hostname: app.zahdikafahriza.web.id
    service: http://app:8000
  - hostname: inventory.zahdikafahriza.web.id
    service: http://phpmyadmin:80
  - service: http_status:404
